package com.pan.drl
import com.pan.drl.Test.Message
rule "test01"
    when

    then
       System.out.println("hello world");
end


global java.util.List list

rule "Hello World"
    dialect "mvel"
    when
        m : Message( status == Message.HELLO, message : message )
    then
        System.out.println( message );
//        modify ( m ) { setMessage( "Goodbyte cruel world" ),
//                       setStatus( Message.GOODBYE ) };
    modify ( m ) { message = "Goodbye cruel world",
                   status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
        Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( message );
end
